services:
 web:
   build: .
   working_dir: /data
   command: python calendario.py
   links:
    - calendario
   volumes:
    - .:/data
   ports:
    - "5008:5008"

 db:
  image: mysql:5.7
  environment:
    MYSQLROOT_PASSWORD: mudar123
  ports:
   - "5000:5000"